### 自动求导机制(autograd)
* 如果设置 .requires_grad 为 True，那么将会追踪所有对于该张量的操作
* 当完成计算后通过调用 .backward()，自动计算所有的梯度， 这个张量的所有梯度将会自动积累到 .grad 属性

In [1]:
import torch
#追踪计算历史,默认为false
x = torch.ones(2, 2, requires_grad=True) 
# x.requires_grad_(True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
# 每个张量都有.grad_fn属性，创建了Function
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [11]:
z = y * y * 3
out = z.mean()

print(z,"\n", out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 
 tensor(27., grad_fn=<MeanBackward0>)


### 梯度

In [12]:
# out为一个纯量，.backward()相当于out.backward(torch.tensor(1))
out.backward()
print(x.grad)

a = torch.tensor(1)
print(a)
a.backward()
print(grad)

tensor([[13.5000, 13.5000],
        [13.5000, 13.5000]])
tensor(1)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn