# Pytorch-Learning

### 创建Tensor

In [3]:
import torch

print(torch.__version__)
# 创建随机初始化的张量
x = torch.rand(5, 3)
print(x)

# long型的全0的Tensor
y = torch.zeros(5, 3, dtype=torch.long)
print(y)

x = torch.tensor([5.5, 3.0])
print(x)


1.3.1
tensor([[0.9498, 0.8173, 0.2717],
        [0.1063, 0.1870, 0.5691],
        [0.1894, 0.3725, 0.2241],
        [0.7948, 0.2904, 0.9953],
        [0.2105, 0.7777, 0.8498]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [2]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型
