### 创建张量

In [1]:
import torch
import numpy as np

torch.__version__

'1.6.0'

In [14]:
# 从原始数据python的list或序列中构建
a = torch.FloatTensor([1, 2, 3])
print("a:",a)

# 指定数据维度创建
b = torch.IntTensor(2, 4)
print("b:", b)
b = torch.IntTensor(2, 4).zero_()
print("b:", b)

# 通过已有的张量生成新的张量
x_ones = torch.ones_like(a)   # 保留a的数据结构(结构、类型)属性
print("x_ones: ", x_ones)

x_rand = torch.rand_like(a, dtype=torch.float)  # 重写数据结构类型
print("x_rand: ", x_rand)

# 用python的索引或切片来获取和修改张量
print(b[0][1])

# print(torch.Storage)

a: tensor([1., 2., 3.])
b: tensor([[-412426960,      32577, -412426960,      32577],
        [        32,          0,        128,          0]], dtype=torch.int32)
b: tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
x_ones:  tensor([1., 1., 1.])
x_rand:  tensor([0.9477, 0.4354, 0.5974])
tensor(0, dtype=torch.int32)


In [41]:
# tensor()为python函数
# torch.tensor(data, dtype=None, device=None, requires_grad=False)
# torch.Tensor()为Tensor类函数,为默认类型torch.FloatTensor()

# torch.tensor()可以从data数据部分拷贝，
# 并根据数据类型生成LongTensor,FloatTensor,DoubleTensor
a = torch.tensor([1, 2])
print(a.type())

b = torch.tensor([1.0, 2.0])
print(b.type())

c = torch.tensor(np.zeros(2, dtype=np.float64))
print(c.type())

torch.LongTensor
torch.FloatTensor
torch.DoubleTensor


In [16]:
# 从内向外看，4x5，3个4x5，2个3x4x5
# 理解为图片(bitch, channel, heigh, width)
x = torch.rand(2, 3, 4, 5)
print(x.shape)   #x.size()输出一样
print(x)

# 创建0阶张量
y = torch.tensor(3.1415)
print(y.shape, y.type())

# 创建1阶张量
y = torch.tensor([3])
print(y.size(), y.type())

y = torch.linspace(1, 10, steps=5, out=None) # 5个1-10的数字，均匀间隔
print(y, y.type())

y = torch.logspace(start=1, end=3, steps=5, out=None) #10-1000的区间,均匀间隔
print(y, y.type())

torch.Size([2, 3, 4, 5])
tensor([[[[0.4419, 0.8428, 0.2631, 0.0157, 0.0848],
          [0.5194, 0.0824, 0.9687, 0.0945, 0.7006],
          [0.4351, 0.7840, 0.1971, 0.7122, 0.1910],
          [0.5429, 0.3745, 0.1812, 0.4886, 0.2829]],

         [[0.8811, 0.8688, 0.9069, 0.5204, 0.9048],
          [0.8745, 0.7191, 0.4640, 0.2291, 0.4752],
          [0.2083, 0.7402, 0.5745, 0.0197, 0.2595],
          [0.4050, 0.6325, 0.4026, 0.2219, 0.1433]],

         [[0.2816, 0.1163, 0.6428, 0.8223, 0.2739],
          [0.9785, 0.0603, 0.7511, 0.0035, 0.4648],
          [0.0091, 0.7796, 0.3286, 0.6725, 0.3407],
          [0.6111, 0.5917, 0.3279, 0.9784, 0.6611]]],


        [[[0.1865, 0.2501, 0.6886, 0.9537, 0.3545],
          [0.1333, 0.6596, 0.7174, 0.3969, 0.3203],
          [0.4217, 0.3924, 0.3141, 0.6563, 0.1456],
          [0.0706, 0.8188, 0.4466, 0.2783, 0.9966]],

         [[0.8449, 0.7769, 0.2807, 0.4947, 0.8061],
          [0.8688, 0.0728, 0.7352, 0.4844, 0.7709],
          [0.2897, 0.7202, 0.

In [3]:
a = torch.ones(3, 2, out=None)  # (*size定义输入形状, out=None)
print(a, a.type())

d = torch.zeros(1, out=a)      # out表示结果同时赋给c
print("a:", a)
print("d:", d)

a = torch.rand(3, out=None)    #(*size, out=None)
print(a, a.type())

a1 = torch.rand([2, 2])        # *size接收列表也读取出数据
print("a1:", a1)                 

a = torch.randn(3, 2, out=None)       # 标准正态分布
print(a)

a = torch.randperm(10, out=None)      # 返回一个0-n-1的随机整数排列
print(a)

a = torch.arange(1,10,2)    #(satrt,end,step=1步长,out=None) 返回长度为end-start/step
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) torch.FloatTensor
a: tensor([0.])
d: tensor([0.])
tensor([0.3642, 0.3181, 0.7168]) torch.FloatTensor
a1: tensor([[0.8788, 0.1425],
        [0.9743, 0.4818]])
tensor([[ 0.8913, -0.7302],
        [ 2.8133, -0.4122],
        [-0.2524,  1.5621]])
tensor([2, 8, 0, 7, 9, 4, 6, 5, 1, 3])
tensor([1, 3, 5, 7, 9])


### 基本类型
* tensor和numpy数据不同是能否在GPU运行，但可以转换以解决该问题
* float 32 torch.FloatTensor  torch.cuda.FloatTensor
* double 64 torch.DoubleTensor
* half   16  N                torch.cuda.HalfTensor
* long   64 torch.LongTensor
* int    32 torch.IntTensor
* short  16 torch.ShortTensor
* char    8 torch.CharTensor
* byte    8 torch.ByteTensor
* torch.Tensor为默认类型（torch.FloatTensor）

In [10]:
# 输出数据类型
a = torch.LongTensor(1)
print(type(a))    # python内置函数
print(a.type())   # Tensor类的成员函数
print(isinstance(a, torch.FloatTensor))

print("a.dtype: ", a.dtype)
print("a.device: ", a.device)

<class 'torch.Tensor'>
torch.LongTensor
False
a.dtype:  torch.int64
a.device:  cpu


In [16]:
# 数据类型转换
# 1.直接调用方法 long() int() double() float() byte()
# 2.用成员函数type()
# 3.a1.type_as(a2)   将a1转换为a2类型
b = a.int()      # 不会改变a的值
print(a.type())
print(b.type())

c = a.type(torch.IntTensor)
print(c.type())

torch.LongTensor
torch.IntTensor
torch.IntTensor


In [10]:
# 高精度显示，item（）返回浮点型数据，在loss和accuracy用
print(y.item())
print(x[0,0,0,0].item())

3.1414999961853027
0.9253968000411987


In [53]:
# Tensor与ndarray转换
a = torch.IntTensor(3)
b = torch.tensor(3.1)
print(a)
numpy_a = a.numpy()   # Tensor转换为numpy
print(numpy_a)

numpy_b = np.array([
    [1,2], [3,4], [5,6]
])
print(numpy_b)
torch_b = torch.from_numpy(numpy_b) # numpy转化为tensor
print(torch_b)


tensor([  795348256,       32511, -1489461408], dtype=torch.int32)
[  795348256       32511 -1489461408]
[[1 2]
 [3 4]
 [5 6]]
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# cpu -> Gpu Tensor.cuda()
# Gpu -> cpu Tensor.cpu()

if torch.cuda.is_available():  # 判断是否支持ＧＰＵ
    input = a.cuda()
else:
    input = a
    

### 张量运算

In [16]:
# 张量逐个元素乘积
m = a.mul(a)         # 等价写法 a*a
print("a: ", a, "\n", "m: ", m)

# 张量矩阵乘法
n = a.matmul(a.T)    # 等价写法 a @ a.T
print("n: ", n)


a:  tensor([1., 2., 3.]) 
 m:  tensor([1., 4., 9.])
n:  tensor(14.)


In [ ]:
# 逐元素除以标量value
torch.div(input, value, out=None)

In [39]:
# 拼接 torch.cat()
x = torch.randn(2, 3)

print(x)
print(torch.cat((x, x, x), 0))  # torch.cat(input张量, dimension按照此维拼接)
print(torch.cat((x, x, x), 1))

# 分块 torch.chunk
print(torch.chunk(x, 2, 0))    # (input, 块数，维度) 按照给定维度分块


tensor([[-1.7674, -0.0617, -0.9939],
        [-1.7520,  0.9254,  1.2600]])
tensor([[-1.7674, -0.0617, -0.9939],
        [-1.7520,  0.9254,  1.2600],
        [-1.7674, -0.0617, -0.9939],
        [-1.7520,  0.9254,  1.2600],
        [-1.7674, -0.0617, -0.9939],
        [-1.7520,  0.9254,  1.2600]])
tensor([[-1.7674, -0.0617, -0.9939, -1.7674, -0.0617, -0.9939, -1.7674, -0.0617,
         -0.9939],
        [-1.7520,  0.9254,  1.2600, -1.7520,  0.9254,  1.2600, -1.7520,  0.9254,
          1.2600]])
(tensor([[-1.7674, -0.0617, -0.9939]]), tensor([[-1.7520,  0.9254,  1.2600]]))


In [50]:
# torch.abs(input, out=None)
print(torch.abs(torch.FloatTensor([-1, 2, -3])))

# torch.add(input, value每个元素都加上该值, output)
a = torch.ones(2, 2)
print(torch.add(a, 1, out=None))
print("a:", a)
# (input, value, other, out) out=input+(other*value)
b = torch.zeros(2, 2)
c = torch.ones(2, 2)
torch.add(a, 2, c, out=b)
print("b:", b)

tensor([1., 2., 3.])
tensor([[2., 2.],
        [2., 2.]])
a: tensor([[1., 1.],
        [1., 1.]])
b: tensor([[3., 3.],
        [3., 3.]])


In [9]:
# view
a = torch.rand(2, 3)
print("a:", a)
print("a.view(1,6)", a.view(1,6))
print("a.view(6,1)", a.view(6,1))

# 某个维度-1代替，自动计算大小
a = torch.rand(2, 3, 4)
print(a.view(3, -1, 2).size())
print(a.view([3, 2, -1]).size())
# print(a.view(3, 5, -1).size()) error
print(a.view(3, -1).size())

a: tensor([[0.2725, 0.4186, 0.8075],
        [0.3155, 0.5448, 0.1719]])
a.view(1,6) tensor([[0.2725, 0.4186, 0.8075, 0.3155, 0.5448, 0.1719]])
a.view(6,1) tensor([[0.2725],
        [0.4186],
        [0.8075],
        [0.3155],
        [0.5448],
        [0.1719]])
torch.Size([3, 4, 2])
torch.Size([3, 2, 4])
torch.Size([3, 8])
